export * from './student-list.component';
export * from './student.service';
export * from './student';
export * from './student-register.component';
export * from './student-update.component';
export * from './student-updateform.component';
export * from './study';
export * from './student-confirm.component';
export * from './student-filter.pipe';
