export * from './student.component';
export * from './student.service';
export * from './student';
export * from './student-register.component';
export * from './filter.pipe';
export * from './student-update.component';
export * from './student-updateform.component';
export * from './object.pipe';
export * from './study';
